# Generated by Django 3.0.3 on 2020-03-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200305_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='id_products'),
        ),
    ]
