# Generated by Django 3.0.3 on 2020-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200306_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='', verbose_name='id_products'),
        ),
    ]
