# Generated by Django 3.0.3 on 2020-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200306_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoiseToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_match_products', models.IntegerField()),
                ('id_product', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
